TrendPie/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.AccessControl;
using System.Text;
using System.Web;
using System.Web.Mvc;
using TrendPie.Models;
using TrendPie.Repositories;
using TrendPie.Services;

namespace TrendPie.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ActiveInfluencers()
        {
            List<User> viewModel = UserRepository.GetAllActive();

            return View(viewModel);
        }

        public ActionResult PendingInfluencers()
        {
            List<User> viewModel = UserRepository.GetAllPending();

            return View(viewModel);
        }

        public ActionResult UserProfile(int userID)
        {
            User viewModel = UserRepository.GetByID(userID);

            return View(viewModel);
        }
        [HttpPost]
        public ActionResult UserProfile(User user)
        {
            UserRepository.UpdateStatus(user.Id, user.Status);
            if (user.AmountPerCampaign != null)
            {
                UserRepository.UpdateAmountPerCampaign(user.Id, user.AmountPerCampaign.Value);
                UserRepository.ClearAmountPerCampaignRequested(user.Id);
            }

            return RedirectToAction("PendingInfluencers");
        }

        public ActionResult CreateCampaign()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateCampaign(Campaign campaign)
        {
            if (ModelState.IsValid)
            {
                campaign.StartDate = DateTime.Parse(campaign.StartDay + "/" + campaign.StartMonth + "/" + campaign.EndYear);
                campaign.EndDate = DateTime.Parse(campaign.EndDay + "/" + campaign.EndMonth + "/" + campaign.EndYear);

                CampaignRepository.Create(campaign);
            }
            return RedirectToAction("CurrentCampaigns");
        }

        public ActionResult EditCampaign(int campaignID)
        {
            Campaign campaign = CampaignRepository.GetById(campaignID);

            return View(campaign);
        }

        [HttpPost]
        public ActionResult EditCampaign(Campaign campaign)
        {
            CampaignRepository.Update(campaign);

            return RedirectToAction("CurrentCampaigns");
        }

        public ActionResult CurrentCampaigns()
        {
            var viewModel = CampaignRepository.GetAllActive();

            return View(viewModel);
        }

        public ActionResult CompleteCampaigns()
        {
            var viewModel = CampaignRepository.GetAllComplete();

            return View(viewModel);
        }

        public ActionResult PayoutReport()
        {
            var viewModel = new List<PayoutReportViewModel>();
            var campaigns = CampaignRepository.GetAllCreatedInLast30Days().OrderByDescending(i => i.DateCreated);

            foreach (var campaign in campaigns)
            {
                var payoutReport = new PayoutReportViewModel
                {
                    Campaign = campaign
                };

                var userCampaigns = UserCampaignRepository.GetAllForCampaign(campaign.Id);

                foreach (var userCampaign in userCampaigns)
                {
                    var user = UserRepository.GetByID(userCampaign.UserID);
                    if (user != null) payoutReport.Users.Add(user);
                }

                viewModel.Add(payoutReport);
            }

            return View(viewModel);
        }

        public FileContentResult Export(int campaignID)
        {
            var file = new StringBuilder();
            var campaign = CampaignRepository.GetById(campaignID);
            var userCampaigns = UserCampaignRepository.GetAllForCampaign(campaignID);

            if (userCampaigns.Any())
            {
                file.AppendLine(
                    "\"PayPal Email\"," +
                    "\"Rate\"," +
                    "\"Currency\""
                    );
            }

            foreach (var userCampaign in userCampaigns)
            {
                var user = UserRepository.GetByID(userCampaign.UserID);

                if (user != null)
                {
                    file.AppendLine(
                        "\"" + user.PayPalEmail + "\"," +
                        "\"" + user.AmountPerCampaign + "\"," +
                        "\"" + user.Country + "\""
                        );
                }
            }

            return File(new UTF8Encoding().GetBytes(file.ToString()), "text/csv", "mass pay " + campaign.Name + " " + campaign.ShortStartDate.Replace('/', '-') + ".csv");
        }

        public ActionResult EmailCampaignToList(int campaignID)
        {
            if (campaignID > 0)
            {
                EmailService.SendNewCampaignAvailableEmailToUsers(campaignID);
            }

            return RedirectToAction("CurrentCampaigns");
        }
    }
}

TrendPie/Controllers/CampaignsController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using TrendPie.Models;
using TrendPie.Repositories;

namespace TrendPie.Controllers
{
    public class CampaignsController : Controller
    {
        public ActionResult Pending()
        {
            var viewModel = new List<Campaign>();

            if (Session != null)
            {
                var user = (User) Session["User"];

                viewModel = CampaignRepository.GetAllActivePendingForUser(user);
            }

            return View(viewModel);
        }

        public ActionResult Live()
        {
            var viewModel = new List<Campaign>();

            if (Session != null)
            {
                var user = (User) Session["User"];

                viewModel = CampaignRepository.GetAllActiveLiveForUser(user);
            }

            return View(viewModel);
        }

        public ActionResult Complete()
        {
            var viewModel = new List<Campaign>();

            if (Session != null)
            {
                var user = (User)Session["User"];
                viewModel = CampaignRepository.GetAllActiveCompleteForUser(user);
            }

            return View(viewModel);
        }

        public ActionResult Accept(int campaignID)
        {
            var user = (User) Session["User"];

            UserCampaignRepository.AcceptCampaign(campaignID, user.Id);

            List<Campaign> viewModel = CampaignRepository.GetAllPending();

            return RedirectToAction("Pending");
        }
    }
}

TrendPie/Controllers/DashboardController.cs
using System.Web.Mvc;
using TrendPie.Models;
using TrendPie.Repositories;

namespace TrendPie.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Index()
        {
            var viewModel = new DashboardIndexViewModel();
            if (Session != null)
            {
                var user = (User)Session["User"];

                viewModel.CampaignLiveList = CampaignRepository.GetTop5ActiveLiveForUser(user);
                viewModel.CampaignCompleteList = CampaignRepository.GetTop5ActiveCompleteForUser(user);
            }

            return View(viewModel);
        }
    }
}

TrendPie/Controllers/ProfileController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using TrendPie.Models;
using TrendPie.Repositories;

namespace TrendPie.Controllers
{
    public class ProfileController : Controller
    {
        // GET: Profile
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Wallet()
        {
            var user = new User();

            if (Session != null) user = (User) Session["User"];

            return View(user);
        }

        public ActionResult UserProfile()
        {
            var user = new User();

            if (Session != null) user = (User) Session["User"];

            return View(user);
        }
        [HttpPost]
        public ActionResult UserProfile(User user)
        {
            UserRepository.UpdateUserProfile(user);

            return View(user);
        }

        public ActionResult Social()
        {
            List<SocialMediaAccount> viewModel = SocialMediaAccountRepository.GetAll();

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult UpdateWallet(User user)
        {
            var currentUser = (User) Session["User"];

            if (currentUser != null)
            {
                RequestAmountPerCampaignUpdate(user, currentUser);
                UpdatePayPalEmail(user, currentUser);
                currentUser = UserRepository.GetByID(currentUser.Id);
                Session["User"] = currentUser;
            }


            return RedirectToAction("Wallet");
        }

        private static void UpdatePayPalEmail(User user, User currentUser)
        {
            if (user.PayPalEmail != currentUser.PayPalEmail)
            {
                UserRepository.UpdatePayPalEmail(currentUser.Id, user.PayPalEmail);
            }
        }
        private static void RequestAmountPerCampaignUpdate(User user, User currentUser)
        {
            if (user.AmountPerCampaign != currentUser.AmountPerCampaign)
            {
                if (user.AmountPerCampaign != null)
                    UserRepository.RequestAmountPerCampaignUpdate(currentUser.Id, user.AmountPerCampaign.Value);
            }
        }
    }
}

TrendPie/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - TrendPie</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <meta name="viewport" content="width=device-width" />

        <div class="parentWrapper bgimgOne">
            <div class="topWrapper100">
                <div class="userGreeting">welcome back ,</div>
                <div class="logo"></div>
                <div class="SlideM">
                    <div class="mnavBWrapper">
                        <div class="menuBtn"></div>
                    </div>
                    <div class="clearme"></div>
                    <div class="MenuLinks">
                        <div class="menuWrap95">
                            <div class="mnavBWrapper">
                                <div class="closeBtn"></div>
                            </div>
                            <div class="space60"></div>

                            <div class="menuItems"><a href="@Url.Action("CurrentCampaigns", "Admin")">CAMPAIGNS<div class="navArrow"></div></a></div>
                            <div class="childBorderWrap"><div class="childBorder"></div></div>

                            <div class="menuItems"><a href="@Url.Action("PendingInfluencers", "Admin")">INFLUENCERS<div class="navArrow"></div></a></div>
                            <div class="childBorderWrap"><div class="childBorder"></div></div>

                            <div class="menuItems"><a href="@Url.Action("PayoutReport", "Admin")">PAYOUT REPORT<div class="navArrow"></div></a></div>
                            <div class="childBorderWrap"><div class="childBorder"></div></div>

                            <div class="menuItems"><a href="@Url.Action("Logout", "Home")">LOG OUT<div class="navArrow"></div></a></div>
                            <div class="childBorderWrap"><div class="childBorder"></div></div>
                        </div>
                        <div class="clearme"></div>
                        <div class="menuBttmBorder"></div>
                    </div>
                </div>
            </div>
            <div class="clearme"></div>
            <div class="space75"></div>
            <div id="main">
                @RenderBody()
                <div class="clearme"></div>
            </div>
            <div class="clearme"></div>
            <footer>
                <div class="footerWrap100">
                    <div class="footerContentRow">
                        <div class="iconPhone"></div>
                        +1 401 659 6668
                    </div>
                    <div class="footerContentRow">
                        <div class="iconMail"></div>
                        Hello@TrendPie.com
                    </div>
                    <div class="clearme"></div>
                    <div class="legalese">Copyright © 2016, Trend Pie, LLC.</div>
                </div>
                <div class="clearme"></div>
            </footer>
            <div class="clearme"></div>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

<script>
    $(document).ready(function () {
        $(".SlideM .MenuLinks").eq(0).hide();

        $(".SlideM .menuBtn").click(function () {
            $(".SlideM .MenuLinks").slideToggle("fast");
        });

        $(".SlideM .closeBtn").click(function () {
            $(".SlideM .MenuLinks").slideToggle("fast");
        });
    });
</script>

TrendPie/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - TrendPie</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <meta name="viewport" content="width=device-width" />

        <div class="parentWrapper bgimgOne">
            <div class="topWrapper100">
                <div class="userGreeting">welcome back ,</div>
                <div class="logo"></div>
                <div class="SlideM">
                    <div class="mnavBWrapper">
                        <div class="menuBtn"></div>
                    </div>
                    <div class="clearme"></div>
                    <div class="MenuLinks">
                        <div class="menuWrap95">
                            <div class="mnavBWrapper">
                                <div class="closeBtn"></div>
                            </div>
                            <div class="space60"></div>

                            <div class="menuItems"><a href="@Url.Action("Index", "Dashboard")">DASHBOARD<div class='navArrow'></div></a></div>
                            <div class="childBorderWrap"><div class="childBorder"></div></div>

                            <div class="menuItems"><a href="@Url.Action("Pending", "Campaigns")">CAMPAIGNS<div class="navArrow"></div></a></div>
                            <div class="childBorderWrap"><div class="childBorder"></div></div>

                            <div>
                                <div class="menuItems"><a href="@Url.Action("Wallet", "Profile")">Wallet<div class="navArrow"></div></a></div>
                                <div class="childBorderWrap"><div class="childBorder"></div></div>
                            </div>

                            <div class="menuItems navhighlight"><a href="@Url.Action("UserProfile", "Profile")">PROFILE<div class="navArrow"></div></a></div>
                            <div class="childBorderWrap"><div class="childBorder"></div></div>

                            <div class="menuItems navhighlight"><a href="@Url.Action("Logout", "Home")">LOG OUT<div class="navArrow"></div></a></div>
                            <div class="childBorderWrap"><div class="childBorder"></div></div>
                        </div>
                        <div class="clearme"></div>
                        <div class="menuBttmBorder"></div>
                    </div>
                </div>
            </div>
            <div class="clearme"></div>
            <div class="space75"></div>
            <div id="main">
                @RenderBody()
                <div class="clearme"></div>
            </div>
            <div class="clearme"></div>
            <footer>
                <div class="footerWrap100">
                    <div class="footerContentRow">
                        <div class="iconPhone"></div>
                        +1 401 659 6668
                    </div>
                    <div class="footerContentRow">
                        <div class="iconMail"></div>
                        Hello@TrendPie.com
                    </div>
                    <div class="clearme"></div>
                    <div class="legalese">Copyright © 2016, Trend Pie, LLC.</div>
                </div>
                <div class="clearme"></div>
            </footer>
            <div class="clearme"></div>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

<script>
    $(document).ready(function () {
        $(".SlideM .MenuLinks").eq(0).hide();

        $(".SlideM .menuBtn").click(function () {
            $(".SlideM .MenuLinks").slideToggle("fast");
        });

        $(".SlideM .closeBtn").click(function () {
            $(".SlideM .MenuLinks").slideToggle("fast");
        });
    });
</script>

TrendPie/Views/Shared/_LoginLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <meta name="viewport" content="width=device-width" />

    <div class="parentWrapper bgimgOne">
        <div class="topWrapper100">
            <div class="space10"></div>
            <div class="logoLG"></div>
        </div>
        <div class="clearme"></div>
        <div class="space150"></div>
        <div id="main">
            @RenderBody()
            <div class="clearme"></div>
        </div>
        <div class="clearme"></div>
        <footer>
            <div class="footerWrap100">
                <div class="footerContentRow">
                    <div class="iconPhone"></div>
                    +1 401 659 6668
                </div>
                <div class="footerContentRow">
                    <div class="iconMail"></div>
                    Hello@TrendPie.com
                </div>
                <div class="clearme"></div>
                <div class="legalese">Copyright © 2016, Trend Pie, LLC.</div>
            </div>
            <div class="clearme"></div>
        </footer>
        <div class="clearme"></div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>